# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Lab1_Jarvis_Rob.py
# Created on: 2013-09-06 20:07:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
Parcel = "E:\\GIS_450\\Database\\Corvallis.gdb\\Parcel"
Schools = "E:\\GIS_450\\Database\\Corvallis.gdb\\Schools"
Parks = "E:\\GIS_450\\Database\\Corvallis.gdb\\Parks"
Railroad = "E:\\GIS_450\\Database\\Corvallis.gdb\\Railroad"
Residential_Parcels = "C:\\Users\\Rob\\Documents\\ArcGIS\\Default.gdb\\Parcel_Select"
schoolBuffer = "C:\\Users\\Rob\\Documents\\ArcGIS\\Default.gdb\\Schools_Buffer"
parksBuffer = "C:\\Users\\Rob\\Documents\\ArcGIS\\Default.gdb\\Parks_Buffer"
railroadBuffer = "C:\\Users\\Rob\\Documents\\ArcGIS\\Default.gdb\\Railroad_Buffer"
schoolResClip = "C:\\Users\\Rob\\Documents\\ArcGIS\\Default.gdb\\Schools_Buffer_Clip1"
schoolParksRes = "C:\\Users\\Rob\\Documents\\ArcGIS\\Default.gdb\\Parks_Buffer_Clip"
residentialParcels = "C:\\Users\\Rob\\Documents\\ArcGIS\\Default.gdb\\Railroad_Buffer_Erase"

# Process: Buffer (2)
arcpy.Buffer_analysis(Parks, parksBuffer, "0.5 Miles", "FULL", "ROUND", "NONE", "")

# Process: Buffer
arcpy.Buffer_analysis(Schools, schoolBuffer, "0.5 Miles", "FULL", "ROUND", "NONE", "")

# Process: Select
arcpy.Select_analysis(Parcel, Residential_Parcels, "\"BENTON_ZON\" LIKE 'R%'")

# Process: Clip
arcpy.Clip_analysis(schoolBuffer, Residential_Parcels, schoolResClip, "")

# Process: Clip (2)
arcpy.Clip_analysis(parksBuffer, schoolResClip, schoolParksRes, "")

# Process: Buffer (3)
arcpy.Buffer_analysis(Railroad, railroadBuffer, "0.5 Miles", "FULL", "ROUND", "NONE", "")

# Process: Erase
arcpy.Erase_analysis(schoolParksRes, railroadBuffer, residentialParcels, "")

